apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: dev-team-alpha-ns
spec:
  serviceAccountName: flux
  releaseName: podinfo
  targetNamespace: apps
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
  interval: 5m
