---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-team-alpha-subnamespaces
  namespace: dev-team-alpha-ns
spec:
  serviceAccountName: flux
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: dev-team-alpha
  prune: true
  path: /base/subnamespaces
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-team-alpha-resources
  namespace: dev-team-alpha-ns
spec:
  serviceAccountName: flux
  interval: 5m
  dependsOn:
    - name: dev-team-alpha-subnamespaces
      namespace: dev-team-alpha-ns
  sourceRef:
    kind: GitRepository
    name: dev-team-alpha
  prune: true
  path: /base/manifests
